version: '3.9'

services:
  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: marketing_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  python:
    build: ./python
    container_name: python
    depends_on:
      - mysql
    volumes:
      - ./python:/app  
    ports:
      - "8050:8050"

volumes:
  mysql-data:
